import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex">
          <div className="shrink-0 grow-0 m basis-auto md:basis-72 p-2 md:p-5 px-2 md:px-6 bg-green-500 h-screen">
            {/* <Navbar /> */}
          </div>
          <div className="justify-self-stretch w-full h-screen bg-white overflow-y-scroll">
            {/* <Routes>
              <Route path="/" element={<HomePage />} />
              <Route path="portfolio" element={<PortfolioPage />} />
              {portfolio.map(p => (
                <Route path={p.href} element={<p.component />} />
              ))}
            </Routes> */}
          </div>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          asddasdas
        </a>
      </footer>
    </div>
  )
}
